# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNa103ns6_Kq8tkwVUGizSZuJuYPvT_J
"""

sum=0
for i in range(1,31):
  sum= sum+i**2+1
print(sum)

sum = 0
for i in range(10,31) :
  for j in range(1,6):
    sum=sum+i*j
print(sum)

sum = 0
for i in range(1,101) :
  if i%3 ==0 or i%4 ==0 :
    continue;
  sum=sum+i
print(sum)

k=0
temp=0
for i in range (1,101) :
  k=k+i
  temp=temp+k
  
print(temp)

for i in range(1,7):
  for j in range(1,7):
    if (i+j)==6 :
      print(i , j)

for i in range(2,101) :
    for j in range(3,i):
        if i%j ==0:
           continue;
    print(i)